set fenc=utf-8
set nobackup
set noswapfile
set autoread
set hidden
set showcmd

set number
set cursorline
set virtualedit=onemore
set smartindent
set visualbell
set showmatch
set laststatus=2
set wildmode=list:longest

nnoremap j gj
nnoremap k gk

syntax enable
highlight Search ctermfg=0 ctermbg=11
highlight IncSearch ctermfg=0 ctermbg=14
set cursorlineopt=line,number
highlight CursorLine cterm=NONE ctermbg=238
highlight CursorLineNr cterm=bold ctermfg=221 ctermbg=238

set list
set listchars=tab:>-
set expandtab
set tabstop=2
set shiftwidth=2

set ignorecase
set smartcase
set incsearch
set wrapscan
set hlsearch

nmap <Esc><Esc> :nohlsearch<CR><Esc>

augroup markdown_list
  autocmd!
  autocmd FileType markdown setlocal comments=b:*,b:-,b:+,n:>
  autocmd FileType markdown setlocal formatoptions+=r
augroup END
