# VIM-like pane navigation
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Vim-like copy mode
setw -g mode-keys vi
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-selection-and-cancel

# Show the pane title on each pane border
set -g pane-border-status top
set -g pane-border-format "#{pane_title}"

# Resize pane
bind -n M-Left resize-pane -L
bind -n M-Right resize-pane -R
bind -n M-Up resize-pane -U
bind -n M-Down resize-pane -D
bind -n M-h resize-pane -L
bind -n M-j resize-pane -D
bind -n M-k resize-pane -U
bind -n M-l resize-pane -R

# macOS clipboard integration
set -g set-clipboard on

# connect tmux copy-mode to macOS clipboard
bind -T copy-mode-vi y send -X copy-pipe-and-cancel "pbcopy"
